// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_QKciNi8NehItHfH0LcPOAIT9WU1MkGw',
    appId: '1:930964686687:web:4a044b440b7d6cae7658ea',
    messagingSenderId: '930964686687',
    projectId: 'realest-3a0d2',
    authDomain: 'realest-3a0d2.firebaseapp.com',
    storageBucket: 'realest-3a0d2.firebasestorage.app',
    measurementId: 'G-KNZJM2L78C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAze4JrdsICIomZfTP4pzneXQYSLwKVFfA',
    appId: '1:930964686687:android:a06eccd6a61ebf627658ea',
    messagingSenderId: '930964686687',
    projectId: 'realest-3a0d2',
    storageBucket: 'realest-3a0d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNxokM0gYFW4N3MQ2A5KYDOOXZ-Ve3NI',
    appId: '1:930964686687:ios:6556928050865a3b7658ea',
    messagingSenderId: '930964686687',
    projectId: 'realest-3a0d2',
    storageBucket: 'realest-3a0d2.firebasestorage.app',
    androidClientId: '930964686687-qb073f6ebitcpkbk7lvfa5alprvncmro.apps.googleusercontent.com',
    iosClientId: '930964686687-qofvkcei21t7e7n9rt77g75ae3bcilot.apps.googleusercontent.com',
    iosBundleId: 'com.example.realest',
  );

}