name: Flutter CI/CD

on:
  push:
    branches:
      - 'REAL-*'  # Matches feature branches named like REAL-1234
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    name: Build & Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # Update with your Flutter version
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Static Analysis
        run: flutter analyze
        continue-on-error: true

      - name: Run Tests
        run: flutter test

      - name: Build APK (Feature Branch)
        if: startsWith(github.ref, 'refs/heads/REAL-')
        run: flutter build apk --debug

      - name: Build APK (Develop)
        if: github.ref == 'refs/heads/develop'
        run: flutter build apk --release

      - name: Build APK (Main)
        if: github.ref == 'refs/heads/main'
        run: flutter build apk --release

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
